### PR TITLE
Revert "File download scans and urls"

### PR DESCRIPTION
**Pull request by hayden-fr**
Reverts hayden-fr/ComfyUI-Model-Manager#28

@cdb-boop This time the markdownify dependency was added to the PR. I think this is not a good idea. Failure to install the dependencies will cause the extension to fail to load, which will cause some additional burden on users. 
Not everyone will install dependencies, especially those using portable versions of Windows.
I didn't notice this at first, so now I've reverted the commit.

### CODE REVIEW

**Comment by cdb-boop** [comment]
Markdown was added to the front end and that forced my hand to add that dependency to parse server-side in order to do scanning in bulk. It is not practical to send model information to the browser to parse and then send it back to the server.

I was under the impression that the ComfyUI Manager handled installing dependencies on update.

**Comment by cdb-boop** [comment]
Do you have a suggestion for how to work around this that does not create a subpar user experience? Otherwise, I will leave it as is.

**Comment by hayden-fr** [comment]
> I was under the impression that the ComfyUI Manager handled installing dependencies on update.

I didn't find that it can automatically handle dependencies, at least it reported an error after I updated it. Then other people may have this problem too.

> Do you have a suggestion for how to work around this that does not create a subpar user experience? Otherwise, I will leave it as is.

I will find a way to solve this problem on the front end.

Actually I'm trying to refactor this project, maybe there is a better solution.

**Comment by cdb-boop** [comment]
Okay, sounds good. There might be a way to tell ComfyUI to install packages, since other nodes manage to get updated, but I'm not familiar.

I'll try not to make any more changes except bug fixes. It is in need of a good refactor.

**Comment by cdb-boop** [comment]
Just some thoughts I'd like to add if you're working on redoing the UI.

* Is it possible to use Vue/Vue Components that the new UI is using, or is it better to have a custom, non-standard solution to work with other UIs?
* I was thinking before about doing something similar to what is in the official UI dev model viewer, with a nested file list. However, I think I'd be nice to also have "all previews", "local list" and "local folder" views too. The nested file list might want to have a hovering image popup for the image like what pythongosssss has done.
* Ideally make it flexible enough to open in a new window (with a more limited set of functionality) or move be able to optionally add it to the sidebar. Also, it might be better to separate the downloader into a different tab in the sidebar.
* Use the built-in settings rather than the custom one being used now. Ideally, everything would be able to dynamically update when appropriate.

**Comment by hayden-fr** [comment]
Yes, the new UI uses Vue and maintains the same technology stack as [ComfyUI_frontend](https://github.com/Comfy-Org/ComfyUI_frontend), such as using the Primevue component library. Now the main interface work on the front end has been completed and some details are being optimized.

This is a preview of the new UI

image

**Comment by cdb-boop** [comment]
Sounds good as long as you think it can work with the various ComfyUI front ends.

The screenshot looks good and more in line with the ComfyUI design. I know it's not ready, but one comment I'd make is that I'd prefer the search bar to be as wide as possible.

Also, I forgot to add it to my list, but depending on performance, I was previously considering adding pagination to help with performance on low-power devices.

**Pull request merged**
