### PR TITLE
Refactor the code structure and optimize the UI.

### PR DESCRIPTION
**Pull request by hayden-fr**
The code has been restructured to be edited more easily.

The new UI is built with Vue. It‘s more appealing and more flexible to operate. The response time has also been shortened.

However, I did not submit the web dist. So after git clone the repo, users need to install dependencies and run build or dev.  It is hoped that this problem can be solved by adding release.

TODO：
- Use github's workflow to add release
- Judge some  in runtime
- If the source code is used, the latest release will be downloaded automatically. 
- If release is used, update checking will be performed automatically. The users can choose to update the release manually or automatically.

Comments welcomed!

### CODE REVIEW

**Comment by cdb-boop** [comment]
On mobile the README example images are getting distorted.

IMG_5404

**Comment by cdb-boop** [comment]
Load times on my end are pretty bad. A consistent 25 second wait on page load/refresh and each model refresh.

**Comment by hayden-fr** [comment]
> Load times on my end are pretty bad. A consistent 25 second wait on page load/refresh and each model refresh.

How many models do you have? I think maybe it's because I scanned all the model information at once. I will improve it.

**Comment by cdb-boop** [comment]
I have 1000+ models. That's why I avoided scanning/hashing and opted for querying the OS for files.

The built-in model library avoids this by loading the model types on demand, but this completely prevents search until you manually load the subtypes, which is unacceptable.

I would say you should avoid pushing to main until you get performance similar to the old UI, which is nearly instant. Focus on desktop, although getting mobile working faster than the old one would be a plus.

**Comment by cdb-boop** [comment]
Latest pull and build I'm no longer seeing previews on any model types except Clip and Controlnet (as far as I can tell).

**Comment by hayden-fr** [comment]
> Latest pull and build and I'm no longer seeing previews on any model types except Clip and Controlnet (as far as I can tell).

Can you provide more details, since everything looks fine on my end

Also, has load times been improved?

**Comment by cdb-boop** [comment]
Load times have improved, although it takes 1-3 seconds to open the model manager after pressing the button. It's not really a fair test, since the previews for most model types are not loading.

I am unable to see associated image previews for `Checkpoint, `embedding`, `Lora` and `VAE`. I can see "ControlNet" and "Clip", which makes it seem like an issue with reading diffusion models. I am able to see the official stable diffusion preview images embedded in the checkpoints (which is slow to read from file and could be adding to the slow down). And for whatever reason, I'm not seeing any of my "Unet" models.

Also, a bit of an unrelated nitpick, but is there any reason why the labels for model types don't match the ComfyUI folder names? For example, the UI says "Checkpoint" but the official folder is named "checkpoints".

**Comment by cdb-boop** [comment]
I think I've narrowed the issue down. It has something to do with models in subdirectories. I was incorrect and there are four LoRAs that have previews and the models are all located in `http://localhost:0000/model-manager/preview/loras/0`.

**Comment by hayden-fr** [comment]
> Also, a bit of an unrelated nitpick, but is there any reason why the labels for model types don't match the ComfyUI folder names? For example, the UI says "Checkpoint" but the official folder is named "checkpoints".

There's nothing special about this, it's just a little quirk of mine. Checkpoints is plural and Checkpoint is singular, that's all. In addition, the UI refers to civitai, so the display name is basically consistent with civitai.

> Load times have improved, although it takes 1-3 seconds to open the model manager after pressing the button. It's not really a fair test, since the previews for most model types are not loading.

About this, I thinkI know what the problem is. Loading thousands of dom nodes is huge problem for the front end.  I apologize for not considering the possibility of such a large number of models beforehand. I will fix it with lazy load.

ComfyUI merged the unet model into diffusion_models, but I did not handle this relationship. This was my mistake.

**Comment by hayden-fr** [comment]
Can you provide the directory structure of your models and the model preview url in web

**Comment by cdb-boop** [comment]
> so the display name is basically consistent with civitai.

I think is should be consistent with ComfyUI, rather than third parties.

> Can you provide the directory structure of your models and the model preview url in web

It's nested folders. There are too many to provide the whole thing, but here's an example: `sd/xl/style/example.safetensors`,  and again, there is no preview; It's using the default.

**Comment by sansmoraxz** [comment]
> If the source code is used, the latest release will be downloaded automatically.

Let's not put this as default. If they want they can probably use comyui manager or update the repo manually.

**Comment by sansmoraxz** [comment]
@hayden-fr can you incorporate some virtual renderer such as this [virtualscroller](https://primevue.org/virtualscroller/)

Might help with large amount of data. As long as the issue is client side and not server side.

**Comment by sansmoraxz** [comment]
@hayden-fr  You may wanna add GHA permissions to the job.

```yaml
    permissions:
      contents: read
      packages: write
      # The next one may not be needed
      id-token: write
```

**Pull request merged**
